class English {
  Map<String, String> get() {
    return {
      'app_name': 'VPN Planet',
      'cz_name' : 'Czech Republic',
      'fr_name' : 'France',
      'br_name' : 'Brazil',
      'ca_name' : 'Canada',
      'gb_name' : 'England',
      'fi_name' : 'Finland',
      'de_name' : 'Germany',
      'hk_name' : 'Hong Kong',
      'jp_name' : 'Japan',
      'us_name' : 'USA',
      'smart_location': 'Smart Location',
      'main_connecting': 'Connection ...',
      'main_disconnecting': 'Disconnection ...',
      'main_connected': 'Connection is protected',
      'main_disconnected': 'Connection is not secured',
      'main_connect' : 'Tap to connect',
      'main_disconnect' : 'Tap to disconnect',
      'main_traffic_in' : 'Mb/s',
      'main_traffic_out' : 'Mb/s',
      'countries_title' : 'Choose the server',
      'countries_connected' : 'Connected',
      'countries_connecting' : 'Connecting...',
      'countries_disconnecting' : 'Disconnecting...',
      'main_menu_server' : 'Server List',
      'main_menu_tariff' : 'Tariff',
      'main_menu_rate' : 'Rate',
      'main_menu_about' : 'About Us',
      'main_menu_terms' : 'Terms & Conditions',
      'main_menu_premium' : 'Remove annoying ads and unlock more locations!',
      'article_about_title' : 'About us',
      'article_terms_title' : 'Terms & Conditions',
      'rate_title' : 'Enjoying VPN Planet?',
      'rate_todo' : 'Rate Us',
      'premium_button' : 'Premium',
      'premium_title_text' : 'Get premium today!',
      'premium_title_description' : 'Remove ads and unlock all location',
      'premium_ad_one_text' : 'Faster Connection',
      'premium_ad_one_description' : 'Up to 1000 Mb/s bandwith to explore',
      'premium_ad_two_text' : 'No Ads',
      'premium_ad_two_description' : 'Have fun surfing without annoying ads',
      'premium_ad_three_text' : '10+ Servers',
      'premium_ad_three_description' : 'Choose any of servers',
      'premium_plan_month_text' : 'Free Trial - 3 days',
      'premium_plan_month_description' : '3 days free trial.\nAfter 3,99\$/month',
      'premium_plan_year_text' : 'Subscription - 1 year',
      'premium_plan_year_description' : '3 days free trial.\nAfter 3,99\$/month or 48,88\$/year',
      'premium_get' : 'Get Premium Now',
      'plan_month_title' : 'Psst!\nSave up to 55%',
      'plan_month_text' : 'Here\'s a chance to save a bunch of money. Choose a yearly subscription and save \$50 per year.',
      'plan_month_button' : 'Upgrade',
      'plan_month_hint' : 'Get 55% off with our 1-year plan. Only \$49.99!',
      'plan_year_title' : 'You Rock!',
      'plan_year_text' : 'Congratulations on going the best tariff!',
      'plan_year_button' : 'Go Home',
      'privacy_title' : 'Privacy Policy',
      'privacy_accept' : 'Accept and continue',
      'privacy_decline' : 'Decline and exit',
      'dialog_decline_text' : 'We cannot proceed\nwithout set permissions',
      'dialog_decline_button' : 'Try Again',
      'dialog_error_title' : 'Oops!',
      'dialog_error_text' : 'Something went wrong.\nPlease, try again.',
      'dialog_error_button' : 'Try Again',
      'toast_tariff_has_changed' : 'Your tariff has changed',
      'toast_connection_error' : 'No Internet connection',
    };
  }
}